---
title: "Report Data Processing"
author: "Matt"
date: "2023-04-26"
output: html_document
---

## Packages

```{r Packages}
library(phyloseq)
library(ggplot2)      
library(readxl)    
library(dplyr)   
library(tibble)     
library(tidyr)
library(ggpubr)
library(patchwork)
library(scales)
library(plyr)
library(tidyverse)
library(vegan)
library(scatterpie)
library(smplot2)
library(gridExtra)
library(treemapify)
library(viridis)
library(rstudioapi)
library(cowplot)
library(ggallin)
library(data.table)
library(Cairo)
library(Hmisc)
library(corrplot)
library(PerformanceAnalytics)
library(maps)
```

## Data

```{# Data}
# WOA 2018 Annual data set

Phosphate (CSV / 1 degree / Statistical mean / Annual) - https://www.ncei.noaa.gov/data/oceans/WOA/WOA18/DATA/phosphate/csv/all/1.00/WOA18_all_p00mn01.csv.gz

Nitrate (CSV / 1 degree / Statistical mean / Annual) - https://www.ncei.noaa.gov/data/oceans/WOA/WOA18/DATA/nitrate/csv/all/1.00/WOA18_all_n00mn01.csv.gz

Temperature (CSV / 1 degree / Statistical mean / Annual / 2005-2017) - https://www.ncei.noaa.gov/data/oceans/WOA/WOA18/DATA/temperature/csv/A5B7/1.00/WOA18_A5B7_t00mn01.csv.gz

MetaPR2

```

# Base Map

```{r Base Map}

# Import world map data

worldmap <- map_data ("world") 

# Make standard world map

base_world  <- ggplot()+  
  coord_fixed() +
  xlab("") + ylab("") + 
  geom_polygon(data=worldmap, aes(x=long, y=lat, group=group), 
                fill="grey80")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        panel.background = element_rect(fill = 'white', colour = 'white'), 
        axis.line = element_line(colour = "white"), #legend.position="none",
        axis.ticks=element_blank(), axis.text.x=element_blank(),
        axis.text.y=element_blank())
```

# Data manipulation

```{r Data manipulation}

#Import data

asv_sample_raw<-read_tsv('/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/metapr2/Metapr2.tsv', show_col_types = FALSE)
MetaPR2_samples <- read_excel("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/metapr2/samples.xlsx")
WOA23_temp <- fread("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/WOA_temp.csv")
WOA23_nitrate <- fread("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/WOA_nitrate.csv")
WOA23_phosphate <- fread("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/WOA_phosphate.csv")

# Remame columns of WOA data

names(WOA23_temp)[names(WOA23_temp) == "#COMMA SEPARATED LATITUDE"] <- "latitude"
names(WOA23_temp)[names(WOA23_temp) == "LONGITUDE"] <- "longitude"
names(WOA23_temp)[names(WOA23_temp) == "AND VALUES AT DEPTHS (M):0"] <- "0"

names(WOA23_nitrate)[names(WOA23_nitrate) == "#COMMA SEPARATED LATITUDE"] <- "latitude"
names(WOA23_nitrate)[names(WOA23_nitrate) == "LONGITUDE"] <- "longitude"
names(WOA23_nitrate)[names(WOA23_nitrate) == "AND VALUES AT DEPTHS (M):0"] <- "0"

names(WOA23_phosphate)[names(WOA23_phosphate) == "#COMMA SEPARATED LATITUDE"] <- "latitude"
names(WOA23_phosphate)[names(WOA23_phosphate) == "LONGITUDE"] <- "longitude"
names(WOA23_phosphate)[names(WOA23_phosphate) == "AND VALUES AT DEPTHS (M):0"] <- "0"

# Set zone

asv_sample_raw$depth_level <- ifelse(asv_sample_raw$depth_level == "euphotic", "surface", asv_sample_raw$depth_level)
MetaPR2_samples$depth_level <- ifelse(MetaPR2_samples$depth_level == "euphotic", "surface", MetaPR2_samples$depth_level)

```

# MATCH SAMPLES

```{r Improved Matching}

#Take top value of Variable

WOA23_nitrate_coalesce<- cbind(WOA23_nitrate[,1:2],
                                 nitrate = as.data.frame(coalesce(!!!WOA23_nitrate[,3:length(WOA23_nitrate)])))
WOA23_phosphate_coalesce<- cbind(WOA23_phosphate[,1:2],
                                 phosphate = as.data.frame(coalesce(!!!WOA23_phosphate[,3:length(WOA23_phosphate)])))
WOA23_temp_coalesce<- cbind(WOA23_temp[,1:2],
                                 temp = as.data.frame(coalesce(!!!WOA23_temp[,3:length(WOA23_temp)])))

# Rename columns

names(WOA23_phosphate_coalesce)[3] <- "phosphate"
names(WOA23_nitrate_coalesce)[3] <- "nitrate"
names(WOA23_temp_coalesce)[3] <- "temp"
```

```{r Adjust collumns}

#Keep only important columns

WOA23_nitrate_coalesce <- WOA23_nitrate_coalesce[,c("longitude", "latitude", "nitrate")]
WOA23_phosphate_coalesce <- WOA23_phosphate_coalesce[,c("longitude", "latitude", "phosphate")]
WOA23_temp_coalesce <- WOA23_temp_coalesce[,c("longitude", "latitude", "temp")]
```

```{r Match Data by location}

#Merge by minimum coordinate distance

temp_min_dist<- cbind(MetaPR2_samples[,c("longitude","latitude")],
                   index=data.frame(apply(raster::pointDistance(as.matrix(MetaPR2_samples[,c("longitude","latitude")]), 
                                                                as.matrix(WOA23_temp_coalesce[,c("longitude","latitude")]), 
                                                                lonlat = T), 1,which.min)))

nitrate_min_dist<- cbind(MetaPR2_samples[,c("longitude","latitude")],
                   index=data.frame(apply(raster::pointDistance(as.matrix(MetaPR2_samples[,c("longitude","latitude")]), 
                                                                as.matrix(WOA23_nitrate_coalesce[,c("longitude","latitude")]), 
                                                                lonlat = T), 1,which.min)))

phosphate_min_dist<- cbind(MetaPR2_samples[,c("longitude","latitude")],
                   index=data.frame(apply(raster::pointDistance(as.matrix(MetaPR2_samples[,c("longitude","latitude")]), 
                                                                as.matrix(WOA23_phosphate_coalesce[,c("longitude","latitude")]), 
                                                                lonlat = T), 1,which.min)))
```

```{r rename collumns}

# Rename collumns

names(temp_min_dist)<- c("longitude",'latitude',"index")
names(nitrate_min_dist)<- c("longitude",'latitude',"index")
names(phosphate_min_dist)<- c("longitude",'latitude',"index")
```

```{r Add Indexing}

# Add Index for merging

WOA23_nitrate_coalesce$index <- 1:nrow(WOA23_nitrate_coalesce)
WOA23_phosphate_coalesce$index <- 1:nrow(WOA23_phosphate_coalesce)
WOA23_temp_coalesce$index <- 1:nrow(WOA23_temp_coalesce)
```

```{r Link data}

# Merge two data sets by index

nitrate_min_dist<- nitrate_min_dist%>%
  merge(WOA23_nitrate_coalesce, by = 'index', all.x = TRUE)
phosphate_min_dist<- phosphate_min_dist%>%
  merge(WOA23_phosphate_coalesce, by = 'index', all.x = TRUE)
temp_min_dist<- temp_min_dist%>%
  merge(WOA23_temp_coalesce, by = 'index', all.x = TRUE)

#Extract samples data

samples_df_location<- MetaPR2_samples %>%
  dplyr::select(file_code,latitude,longitude)
```


```{r merge datas}

#Merge by Lat/long

asv_sample_woa_temp_location<- samples_df_location %>%
  merge(., temp_min_dist[c(2,3,6)], by.x = c('longitude','latitude'),
        by.y = c("longitude.x","latitude.x"),all.x = T,allow.cartesian=TRUE)%>%
  dplyr::group_by(file_code,longitude,latitude,temp) %>%
  dplyr::summarise(total_count=n(),.groups = 'drop')%>%
  dplyr::select( -total_count) %>%
  dplyr::rename("temp_woa"="temp")%>%
  as.data.frame()

asv_sample_woa_nitrate_location<- samples_df_location %>%
  merge(., nitrate_min_dist[c(2,3,6)], by.x = c('longitude','latitude'),
        by.y = c("longitude.x","latitude.x"),all.x = T,allow.cartesian=TRUE)%>%
  dplyr::group_by(file_code,longitude,latitude,nitrate) %>%
  dplyr::summarise(total_count=n(),.groups = 'drop')%>%
  dplyr::select( -total_count) %>%
  dplyr::rename("nitrate_woa"="nitrate")%>%
  as.data.frame()

asv_sample_woa_phosphate_location<- samples_df_location %>%
  merge(., phosphate_min_dist[c(2,3,6)], by.x = c('longitude','latitude'),
        by.y = c("longitude.x","latitude.x"),all.x = T,allow.cartesian=TRUE)%>%
  dplyr::group_by(file_code,longitude,latitude,phosphate) %>%
  dplyr::summarise(total_count=n(),.groups = 'drop')%>%
  dplyr::select( -total_count) %>%
  dplyr::rename("phosphate_woa"="phosphate")%>%
  as.data.frame()
```

```{r Final Data}

#Marge all together

MetaPR2_samples_merged<-merge(MetaPR2_samples, asv_sample_woa_nitrate_location[,c("file_code","nitrate_woa")], by = c("file_code"), all.x = T)
MetaPR2_samples_merged<-merge(MetaPR2_samples_merged, asv_sample_woa_phosphate_location[,c("file_code","phosphate_woa")], by = c("file_code"), all.x = T)
MetaPR2_samples_merged<-merge(MetaPR2_samples_merged, asv_sample_woa_temp_location[,c("file_code","temp_woa")], by = c("file_code"), all.x = T)
```


# PLOTS

```{r Data}

# Copy
 
sample_info<-MetaPR2_samples_merged

#Trim

asv_sample_raw<-asv_sample_raw[!(asv_sample_raw$division == "Metazoa" | asv_sample_raw$division == "Fungi"),] #Already done at MetaPR2 download stage?
asv_sample<- asv_sample_raw %>%
  dplyr::select(-c("climate"))%>%
  merge(sample_info[,c("file_code","climate","temp_woa","nitrate_woa","phosphate_woa")],by=c('file_code'),all.x = T)

# Data Adjust

names(sample_info)[names(sample_info) == "temperature"] <- "Nitrate_Class"
names(asv_sample)[names(asv_sample) == "temperature"] <- "Nitrate_Class"
names(sample_info)[names(sample_info) == "salinity"] <- "Phosphate_Class"
names(asv_sample)[names(asv_sample) == "salinity"] <- "Phosphate_Class"
names(sample_info)[names(sample_info) == "ice_coverage"] <- "temp_Class"
names(asv_sample)[names(asv_sample) == "ice_coverage"] <- "temp_Class"
asv_sample$nitrate_woa <- asv_sample$nitrate_woa * 62.0049
sample_info$nitrate_woa <- sample_info$nitrate_woa * 62.0049
asv_sample$phosphate_woa <- asv_sample$phosphate_woa * 94.9714
sample_info$phosphate_woa <- sample_info$phosphate_woa * 94.9714

```

```{r Processing Classifications}

#Classify 

asv_sample<-asv_sample %>%
  mutate(depth_level = case_when((depth >=  0 & depth <= 10) ~ "surface",
                                 (depth >  10 & depth <= 200 ) ~ "Euphotic",
                                 (depth >  200) ~ "Pelagic",
                                 TRUE ~ depth_level))
sample_info<-sample_info %>%
  mutate(depth_level = case_when((depth >=  0 & depth <= 10) ~ "surface",
                                 (depth >  10 & depth <= 200 ) ~ "Euphotic",
                                 (depth >  200) ~ "Pelagic",
                                 TRUE ~ depth_level))
asv_sample<-asv_sample %>%
  mutate(Nitrate_Class = case_when((nitrate_woa < 260) ~ 'Oligotrophic',
                                 (nitrate_woa >=  260 & nitrate_woa <= 350 ) ~ 'Mesotrophic',
                                 (nitrate_woa >  350) ~ 'Eutrophic',
                                 ))
sample_info<-sample_info %>%
  mutate(Nitrate_Class = case_when((nitrate_woa < 260) ~ 'Oligotrophic',
                                 (nitrate_woa >=  260 & nitrate_woa <= 350 ) ~ 'Mesotrophic',
                                 (nitrate_woa >  350) ~ 'Eutrophic',
                                 ))
asv_sample<-asv_sample %>%
  mutate(Phosphate_Class = case_when((phosphate_woa < 10) ~ 'Oligotrophic',
                                 (phosphate_woa >=  10 & phosphate_woa <= 30 ) ~ 'Mesotrophic',
                                 (phosphate_woa >  30) ~ 'Eutrophic',
                                 ))
sample_info<-sample_info %>%
  mutate(Phosphate_Class = case_when((phosphate_woa < 10) ~ 'Oligotrophic',
                                 (phosphate_woa >=  10 & phosphate_woa <= 30 ) ~ 'Mesotrophic',
                                 (phosphate_woa >  30) ~ 'Oligotrophic',
                                 ))

asv_sample<-asv_sample %>%
  mutate(temp_Class = case_when((temp_woa < 10) ~ 'Polar',
                                 (temp_woa >=  10 & temp_woa <= 18 ) ~ 'Temperate',
                                 (temp_woa >  18) ~ 'Tropical',
                                 ))
sample_info<-sample_info %>%
  mutate(temp_Class = case_when((temp_woa < 10) ~ 'Polar',
                                 (temp_woa >=  10 & temp_woa <= 18 ) ~ 'Temperate',
                                 (temp_woa >  18) ~ 'Tropical',
                                 ))

#Redo Coastal classification

asv_sample<- asv_sample %>%
  mutate(ecosystem = case_when((dataset_id ==  385) ~ "coastal",
                                 TRUE ~ ecosystem))
sample_info<- sample_info %>%
  mutate(ecosystem = case_when((dataset_id ==  385) ~ "coastal",
                               TRUE ~ ecosystem))
```

```{r Main Distribution Plot}

#Surface only

asv_sample_surface<-asv_sample %>%
  subset(depth_level == 'surface')

#Chloro ID

Chloro_Presence <- asv_sample_surface %>%
  group_by(file_code, latitude, longitude, division, n_reads_pct) %>%
  dplyr::summarise(total_count = n() * n_reads_pct, .groups = 'drop') %>%
  dplyr::select(-n_reads_pct) %>% group_by(file_code, latitude, longitude, division) %>%
  dplyr::summarise(total_count = sum(total_count), .groups = 'drop') %>%
  spread(key = division, value = total_count) %>%
  dplyr::select(file_code, latitude, longitude, Chlorophyta)%>%
  mutate(P_A = case_when((Chlorophyta > 0) ~ "present",
                         is.na(Chlorophyta) ~ "absent"))%>%
  as.data.frame()

#Filter Chloro

Chloro_asv_sample_unnormalised<- filter(asv_sample,division == "Chlorophyta")
Chloro_asv_sample_surface_unnormalised <- filter(asv_sample_surface,division == "Chlorophyta")

#Identify dominant Chlorophyta

dominant_taxon <- Chloro_asv_sample_surface_unnormalised %>%
  group_by(file_code, class, n_reads_pct) %>%
  arrange(file_code, desc(n_reads_pct)) %>%
  group_by(file_code) %>%
  dplyr::slice(1) %>%
  mutate(dominant_taxon = class) %>%
  dplyr::select(file_code, latitude, longitude, dominant_taxon, n_reads_pct)

#Dominant %

dominant_merge <- Chloro_Presence %>%
  merge(dominant_taxon[,c("file_code","dominant_taxon","n_reads_pct")], 
        by=c('file_code'),all.x = T)

```

```{r Plot}
Class_Types <- unique(Chloro_asv_sample_surface_unnormalised$class)
palette1_named = setNames(object = scales::hue_pal()(13), nm = Class_Types)
vir_class <- palette1_named 
# Create the main map
main_map<- base_world +
  geom_point(data=subset(dominant_merge, is.na(dominant_taxon)), 
             aes(x = longitude, 
                 y = latitude,
                 shape='NA'), stroke=0.8, shape=4,color = "red") +
  geom_jitter(data = dominant_merge, aes(x = longitude, 
                                         y = latitude,
                                         color=dominant_taxon,
                                         size = n_reads_pct*2),
              alpha=0.6)+
  guides(size = guide_legend(reverse=T))+
  scale_size_continuous(range  = c(0.1, 10), 
                        limits = c(0, 40), 
                        breaks = c(1, 5, 10),
                        trans=pseudolog10_trans)+
  scale_color_manual(values=vir_class)+
  labs(size="% of microbial \n eukaryotes", color="Dominant taxon")+
  theme_minimal()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        legend.box.background = element_rect(colour = NA),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 20),
        ) 
  
# Adjust graph & Save

main_map <- main_map + guides(color = guide_legend(override.aes = list(size = 5)))

ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/Main_map", ".pdf"),
       plot = main_map,
       width = 40,
       height = 16,
       units = "cm",
       bg = "white")
```

# Treemap + scatterpie map

```{r Normalisation}

# NORMALISED AGAIN

# Calculate the total counts for each sample
Chloro_asv_sample <- Chloro_asv_sample_unnormalised %>%
  dplyr::group_by(file_code) %>%
  dplyr::mutate(n_reads_total = sum(n_reads)) %>%
  dplyr::group_by(file_code) %>%
  dplyr::mutate(n_reads_pct = (n_reads / n_reads_total)*100)


Chloro_asv_sample_surface <- Chloro_asv_sample_surface_unnormalised %>%
  dplyr::group_by(file_code) %>%
  dplyr::mutate(n_reads_total = sum(n_reads)) %>%
  dplyr::group_by(file_code) %>%
  dplyr::mutate(n_reads_pct = (n_reads / n_reads_total)*100)

```


```{r Variables}
# Function to plot treemap + scatterpie map - Redo this in a more logical way

p2_plot <- function(variable) {
  if (variable == "nitrate_woa" | variable == "phosphate_woa" | variable == "temp_woa") {
    df <- Chloro_asv_sample %>%
      subset(depth_level == 'surface')
  } else if (variable == "ecosystem") {
    df <- Chloro_asv_sample %>% 
      mutate(across(ecosystem, factor, levels = c("coastal","oceanic")))
  } 
  
  return(list(df = df, variable = variable))
}

# Call the p2_plot function and extract the resulting df and variable
result_ecosystem <- p2_plot("ecosystem")
df_ecosystem <- result_ecosystem$df
variable_ecosystem <- result_ecosystem$variable  
result_nitrate_woa <- p2_plot("nitrate_woa")
df_nitrate_woa <- result_nitrate_woa$df
variable_nitrate_woa <- result_nitrate_woa$variable  
result_temp_woa <- p2_plot("temp_woa")
df_temp_woa <- result_temp_woa$df
variable_temp_woa <- result_temp_woa$variable  
result_phosphate_woa <- p2_plot("phosphate_woa")
df_phosphate_woa <- result_phosphate_woa$df
variable_phosphate_woa <- result_phosphate_woa$variable  
```

```{r Data Prep}
  
  # Preparing chloro scatterpie data: Relative abundance within class

Chloro_class_ecosystem <- df_ecosystem %>%
  dplyr::select(file_code, any_of(c(variable_ecosystem)), latitude, longitude, class, n_reads_pct) %>%
  dplyr::group_by(file_code, across(any_of(variable_ecosystem)), latitude, longitude, class) %>%
  dplyr::summarise(n_reads_pct = sum(n_reads_pct), .groups = 'drop') %>%
  dplyr::arrange(class, desc(n_reads_pct)) %>%
  pivot_wider(names_from = class, values_from = n_reads_pct, values_fill = 0) %>%
  na.omit() %>%
  as.data.frame()

  
```

``` {r Scatterpie} 
  ### Plotting scatterpie map of coastal/oceanic in class chloro 

#Base Map Test

  Chloro_scatter_all<-base_world+
      geom_scatterpie(aes(x=longitude, y=latitude), 
                      data=Chloro_class_ecosystem,cols=colnames(Chloro_class_ecosystem[,c(5:17)]), 
                      color=NA,alpha=0.8,pie_scale = 0.3)+
      theme(legend.position = "bottom")+
      guides(fill=guide_legend(title="Class"))+
      scale_fill_manual(values=vir_class)

# Seperate Data

Chloro_class_eutro <- subset(Chloro_class_ecosystem, ecosystem %in% c("coastal"))
Chloro_class_oligo <- subset(Chloro_class_ecosystem, ecosystem %in% c("oceanic"))

#Map 1

  Chloro_scatter_eutro<-base_world+
      geom_scatterpie(aes(x=longitude, y=latitude), 
                      data=Chloro_class_eutro,cols=colnames(Chloro_class_eutro[,c(5:17)]), 
                      color=NA,alpha=0.8,pie_scale = 0.3)+
  labs(y = "Coastal", tag = "A") +
      theme(legend.position = "", axis.title = element_text(size = 20))+
      guides(fill=guide_legend(title="Class"))+
      scale_fill_manual(values=vir_class)
  
  #Legend for later formating
  
    Chloro_scatter_eutro_legend<-base_world+
      geom_scatterpie(aes(x=longitude, y=latitude), 
                      data=Chloro_class_eutro,cols=colnames(Chloro_class_eutro[,c(5:17)]), 
                      color=NA,alpha=0.8,pie_scale = 0.3)+
  labs(y = "Coastal", tag = "C") +
      theme(legend.position = "right",
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 20))+
      guides(fill=guide_legend(title="Class"))+
      scale_fill_manual(values=vir_class)
  
legend <- get_legend(Chloro_scatter_eutro_legend)

legend <- as_ggplot(legend)

#Save
  
  ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/Chloro_scatter_coastal", ".pdf"),
       plot = Chloro_scatter_eutro,
       width = 44,
       height = 22,
       units = "cm",
       bg = "white")
  
#Map 2
  
  Chloro_scatter_oligo<-base_world+
      geom_scatterpie(aes(x=longitude, y=latitude), 
                      data=Chloro_class_oligo,cols=colnames(Chloro_class_oligo[,c(5:17)]), 
                      color=NA,alpha=0.8,pie_scale = 0.3)+
  labs(y = "Oceanic", tag = "C") +
      theme(legend.position = "", axis.title = element_text(size = 20))+
      guides(fill=guide_legend(title="Class"))+
      scale_fill_manual(values=vir_class)
  
  #Save
  
  ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/Chloro_scatter_oceanic", ".pdf"),
       plot = Chloro_scatter_oligo,
       width = 44,
       height = 22,
       units = "cm",
       bg = "white")
  
```  

```{r Tree Map}
  ## Part 2.2: Tree map of chloro class subgroup (species)

# Extract Data for X axis pf scatterpie maps

Chloro_oceanic_reads <- Chloro_asv_sample_unnormalised %>%
      subset(ecosystem == 'oceanic') %>%
      summarise(total = sum(n_reads_pct))

Chloro_coastal_reads <- Chloro_asv_sample_unnormalised %>%
      subset(ecosystem == 'coastal') %>%
      summarise(total = sum(n_reads_pct))

Total_oceanic_reads <- asv_sample %>%
      subset(ecosystem == 'oceanic') %>%
      summarise(total = sum(n_reads_pct))

Total_coastal_reads <- asv_sample %>%
      subset(ecosystem == 'coastal') %>%
      summarise(total = sum(n_reads_pct))

# Percentage of total reads

Percentage_oceanic <- (Chloro_oceanic_reads/Total_oceanic_reads)*100
Percentage_coastal <- (Chloro_coastal_reads/Total_coastal_reads)*100


# Rows of df indicate number of samples choro present 

Chloro_oceanic_sites <- Chloro_asv_sample %>%
      subset(ecosystem == 'oceanic') %>%
  distinct(file_code)

Chloro_coastal_sites <- Chloro_asv_sample %>%
      subset(ecosystem == 'coastal') %>%
  distinct(file_code)

  # Preparing chloro treemap data: class and subgroup species nreads

chloro_class_sub <- df_ecosystem %>%
  dplyr::select(file_code, any_of(c(variable_ecosystem)), latitude, longitude, class, species, n_reads_pct) %>%
  group_by(file_code, across(any_of(variable_ecosystem)), class, species) %>%
  dplyr::summarise(n_reads_pct = sum(n_reads_pct), .groups = 'drop') %>%
  drop_na() %>%
  as.data.frame()
  
  ### Plotting treemap of classes and subgroup in class chloro 
  
chloro_class_sub_eutrophic <- subset(chloro_class_sub, ecosystem %in% c("coastal"))
chloro_class_sub_oligotrophic <- subset(chloro_class_sub, ecosystem %in% c("oceanic"))
    
chloro_class_sub_eutrophic_treemap<- ggplot(chloro_class_sub_eutrophic, aes(area = n_reads_pct, 
                                           fill = class,
                                           subgroup = class, 
                                           label = species)) +
  labs(tag = "B", x = "n = 1376, avg % = 9.85%") +
      treemapify::geom_treemap() +
      treemapify::geom_treemap_text(colour = "white", place = "centre", grow = T) +
      treemapify::geom_treemap_subgroup_border() +
      treemapify::geom_treemap_subgroup_text(place = "topleft", grow = T, 
                                             alpha = 0.5, colour = "black", 
                                             min.size = 0) +
      theme_bw() +
      theme(axis.title.x = element_text(size = 15))  +
      scale_fill_manual(values=vir_class)+
      coord_cartesian(xlim = c(50, 350), ylim = c(10, 35), clip = "off")+
      guides(fill = "none") 
    
        
chloro_class_sub_oligotrophic_treemap<- ggplot(chloro_class_sub_oligotrophic, aes(area = n_reads_pct, 
                                           fill = class,
                                           subgroup = class, 
                                           label = species)) +
  labs(tag = "D", x = "n = 1336, avg % = 4.96%") +
      treemapify::geom_treemap() +
      treemapify::geom_treemap_text(colour = "white", place = "centre", grow = T) +
      treemapify::geom_treemap_subgroup_border() +
      treemapify::geom_treemap_subgroup_text(place = "topleft", grow = T, 
                                             alpha = 0.5, colour = "black", 
                                             min.size = 0) +
      theme_bw() +
  theme(axis.title.x = element_text(size = 15)) +
      scale_fill_manual(values=vir_class)+
      coord_cartesian(xlim = c(50, 350), ylim = c(10, 35), clip = "off")+
      guides(fill = "none") 
    
chloro_class_sub_oligotrophic_treemap

# Save

ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/chloro_class_sub_oceanic_treemap", ".pdf"),
       plot = chloro_class_sub_oligotrophic_treemap,
       width = 22,
       height = 22,
       units = "cm",
       bg = "white")
    
  
ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/chloro_class_sub_coastal_treemap", ".pdf"),
       plot = chloro_class_sub_eutrophic_treemap,
       width = 22,
       height = 22,
       units = "cm",
       bg = "white")

# All together Plot

P2 <- Chloro_scatter_oligo
P1 <- Chloro_scatter_eutro
P4 <- chloro_class_sub_oligotrophic_treemap
P3 <- chloro_class_sub_eutrophic_treemap
P5 <- legend

layout <- c(
  area(t = 1, l = 1, b = 2, r = 4), #SCATTER OLIGI
  area(t = 3, l = 1, b = 4, r = 4), #SCATTER EUPH
  area(t = 1, l = 5, b = 2, r = 6), #TREE OLIGI
  area(t = 3, l = 5, b = 4, r = 6), #TREE EUPH
  area(t = 1, l = 7, b = 4, r = 8)) #LEGEND
  
plots_2 <-  P1 + P2 + P3 + P4 + P5 + plot_layout(design = layout)
  

#Save

ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/Scatter_tree_ecosytem", ".pdf"),
       plot = plots_2,
       width = 40,
       height = 22,
       units = "cm",
       bg = "white")


```

# Bar plots

```{r Plots}
# Prepare data for nitrate plot

Chloro_nitrate <- Chloro_asv_sample %>%
  mutate(across(Nitrate_Class, factor, levels=c("oligotrophic","mesotrophic","eutrophic"))) %>%
   filter(depth_level == "surface") %>%
  mutate(nitrate_woa = fct_rev(cut(nitrate_woa, breaks = c(0, 1, 50, 100, 260, 350, 500,750, 1000,1500,2000))))%>%
  drop_na(nitrate_woa)%>%
  group_by(nitrate_woa,class) %>%
  mutate(n_reads_pct = n_reads_pct/sum(n_reads_pct)*100)

# To count the number of samples in each break

nitrate_samples <- Chloro_asv_sample %>% 
  mutate(across(Nitrate_Class, factor, levels=c("oligotrophic","mesotrophic","eutrophic")))%>%
  filter(depth_level == "surface") %>%
 mutate(nitrate_woa = fct_rev(cut(nitrate_woa, breaks = c(0, 50, 100, 260, 350, 500,750, 1000,1500,2000))))%>%
  drop_na(nitrate_woa)%>%
  select(file_code, nitrate_woa) %>% 
  distinct() %>% 
  group_by(nitrate_woa) %>% 
  count() 
  
  # Phosphate

Chloro_phosphate <- Chloro_asv_sample %>%
  mutate(across(Phosphate_Class, factor, levels=c("oligotrophic","mesotrophic","eutrophic"))) %>%
   filter(depth_level == "surface") %>%
  mutate(phosphate_woa = fct_rev(cut(phosphate_woa, breaks = c(0, 5, 10, 15, 20, 25, 30, 50,75,125,200))))%>%
  drop_na(phosphate_woa) %>%
  group_by(phosphate_woa,class) %>%
  mutate(n_reads_pct = n_reads_pct/sum(n_reads_pct)*100)

# To count the number of samples in each break

phosphate_samples <- Chloro_asv_sample %>% 
  mutate(across(Phosphate_Class, factor, levels=c("oligotrophic","mesotrophic","eutrophic")))%>%
  filter(depth_level == "surface") %>%
 mutate(phosphate_woa = fct_rev(cut(phosphate_woa, breaks = c(0, 5, 10, 15, 20, 25, 30, 50,75,125,200))))%>%
  drop_na(phosphate_woa)%>%
  select(file_code, phosphate_woa) %>% 
  distinct() %>% 
  group_by(phosphate_woa) %>% 
  count() 

 # Temp

Chloro_temp <- Chloro_asv_sample %>%
  mutate(across(temp_Class, factor, levels=c("oligotrophic","mesotrophic","eutrophic"))) %>%
   filter(depth_level == "surface") %>%
  mutate(temp_woa = fct_rev(cut(temp_woa, breaks = c(0, 5, 10, 14, 18, 22, 26,30))))%>%
  drop_na(temp_woa) %>%
  group_by(temp_woa,class) %>%
  mutate(n_reads_pct = n_reads_pct/sum(n_reads_pct)*100)


# To count the number of samples in each break

temp_samples <- Chloro_asv_sample %>% 
  mutate(across(temp_Class, factor, levels=c("oligotrophic","mesotrophic","eutrophic")))%>%
  filter(depth_level == "surface") %>%
 mutate(temp_woa = fct_rev(cut(temp_woa, breaks = c(0, 5, 10, 14, 18, 22, 26,30))))%>%
  drop_na(temp_woa)%>%
  select(file_code, temp_woa) %>% 
  distinct() %>% 
  group_by(temp_woa) %>% 
  count() 

# Plotting out nit plot 


Nitrate_final <- ggplot(Chloro_nitrate, aes(x=nitrate_woa,y=n_reads_pct,fill=class)) +
  geom_bar(position="fill",stat="identity") +
  scale_fill_manual(values = palette1_named) + 
  coord_flip() +
  ylab("Relative Abundance") +
  labs(x = expression("Average Annual Nitrate"~(mg/m^-3)),tag = "A") +
  theme(legend.position = "", axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text = element_text(size = 11), strip.text = element_text(size=20)) +
  facet_wrap(~ecosystem) +
  scale_y_continuous(limits = c(0, 1), labels = scales::percent)


# Plotting out pho plot 


Phosphate_final <- ggplot(Chloro_phosphate, aes(x=phosphate_woa,y=n_reads_pct,fill=class)) +
  geom_bar(position="fill",stat="identity") +
  scale_fill_manual(values = palette1_named) + 
  coord_flip() +
  ylab("Relative Abundance") +
  labs(x = expression("Average Annual Phosphate"~(mg/m^-3)), tag = "B") +
  theme(legend.position = "", axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text = element_text(size = 11), strip.text = element_text(size=20)) +
  facet_wrap(~ecosystem) +
  scale_y_continuous(limits = c(0, 1), labels = scales::percent)


# Plotting out temp plot 

temp_final <- ggplot(Chloro_temp, aes(x=temp_woa, y=n_reads_pct, fill=class)) +
  geom_bar(position="fill", stat="identity",) +
  scale_fill_manual(values = palette1_named) + 
  coord_flip() +
  ylab("Relative Abundance") +
  labs(x = expression(paste("Average Annual Temperature"~(phantom()^o*C))),tag = "C") +
  theme(legend.position = "right", axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text = element_text(size = 11), strip.text = element_text(size=20)) +
  facet_wrap(~ecosystem) +
  scale_y_continuous(limits = c(0, 1), labels = scales::percent)

# Plotting out legend
  
  temp_final_NL <- ggplot(Chloro_temp, aes(x=temp_woa, y=n_reads_pct, fill=class)) +
  geom_bar(position="fill", stat="identity",) +
  scale_fill_manual(values = palette1_named) + 
  coord_flip() +
  ylab("Relative Abundance") +
  labs(x = expression(paste("Average Annual Temperature"~(phantom()^o*C))),tag = "C") +
  theme(legend.position = "", axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text = element_text(size = 11), strip.text = element_text(size=20)) +
  facet_wrap(~ecosystem) +
  scale_y_continuous(limits = c(0, 1), labels = scales::percent)

  # save
  
ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/chloro_class_Nitrate_final_bar", ".pdf"),
       plot = Nitrate_final,
       width = 22,
       height = 10,
       units = "cm",
       bg = "white")
    
ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/chloro_class_Phosphate_final_ba", ".pdf"),
       plot = Phosphate_final,
       width = 22,
       height = 16,
       units = "cm",
       bg = "white")
ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/chloro_class_temp_final_ba", ".pdf"),
       plot = temp_final,
       width = 22,
       height = 16,
       units = "cm",
       bg = "white")

# Format plots

plots <- wrap_plots(Nitrate_final, Phosphate_final, temp_final) +
  plot_layout(ncol = 3, nrow = 1, guides = "collect")

layout_2 <- c(
  area(t = 1, l = 1, b = 2, r = 2), #SCATTER OLIGI
  area(t = 1, l = 3, b = 2, r = 4), #SCATTER EUPH
  area(t = 1, l = 5, b = 2, r = 6), #TREE EUPH
area(t = 1, l = 7, b = 2, r = 7)) #LEGEND
  
plots_3 <-  Nitrate_final + Phosphate_final + temp_final_NL + P5 +
    plot_layout(design = layout_2)

#save

ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/Chloro_Bar_WOA", ".pdf"),
       plot = plots,
       width = 66,
       height = 16,
       units = "cm",
       bg = "white",)

ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/Chloro_Bar_WOA_2", ".pdf"),
       plot = plots_3,
       width = 60,
       height = 16,
       units = "cm",
       bg = "white")



```

```{r NMDS}

# Top 200 ASV's

Chloro_asv_sample_surface_top <- Chloro_asv_sample_surface %>%
      subset(depth_level == 'surface')%>%
      drop_na(ecosystem)%>%
      dplyr::select(asv_code,n_reads_pct) %>%
      group_by(asv_code)%>%
      dplyr::summarise(total = sum(n_reads_pct),.groups = 'drop')%>%
      arrange(desc(total))%>%
      dplyr::filter(total >= 200) 

# Make Matrix for NMDS with top ASV's

   chloro_wide_top <- Chloro_asv_sample_surface %>%
      subset(depth_level == 'surface' )%>%
      drop_na(ecosystem)%>%
      dplyr::select(file_code,asv_code,n_reads_pct) %>%
      merge(Chloro_asv_sample_surface_top,., by="asv_code")%>%
      dplyr::select(-total) %>%
      pivot_wider(id_cols = file_code, names_from = asv_code, values_from = n_reads_pct,values_fill = 0) %>%
      as.data.frame()
   
 chloro_wide_top_2 <- chloro_wide_top  # Copy data before altering

# Convert first collumn to ID 
 
samp2 <- chloro_wide_top[,-1]
rownames(samp2) <- chloro_wide_top[,1]
chloro_wide_top <- samp2


#NMDS_Chloro <- metaMDS(chloro_wide[,-c(1)], k = 2, trymax = 40, trace = F, autotransform = FALSE, distance = "bray")

NMDS_Chloro_top <- metaMDS(chloro_wide_top, k = 2, trymax = 100, 
                            trace = F, autotransform = FALSE,
                            distance = "bray")

```


```{r Plot NMDS}

data.scores_norm = as.data.frame(scores(NMDS_Chloro_top)$sites) # Isolate sites from samples scores

NMDS_Chloro_top$points

# data.scores_norm <- data.scores_norm %>% mutate(sample_info = chloro_wide_top$file_code)

data.scores_norm$file_code <- chloro_wide_top_2$file_code
data.scores_norm_info <- left_join(data.scores_norm, sample_info, by= "file_code")

NMDS_plot_ecosystem <- ggplot(data.scores_norm_info, aes(x=NMDS1, y=NMDS2, color=temp_Class)) +
  geom_point() +
  theme_bw() +
theme(axis.text.x = element_blank(),  # remove x-axis text
        axis.text.y = element_blank(), # remove y-axis text
        axis.ticks = element_blank(),  # remove axis ticks
        axis.title.x = element_text(size=18), # remove x-axis labels
        axis.title.y = element_text(size=18), # remove y-axis labels
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank())

NMDS_plot_ecosystem

NMDS1_quantiles <- quantile(data.scores_norm_info$NMDS1, c(0.1, 0.9)) #Trim
NMDS2_quantiles <- quantile(data.scores_norm_info$NMDS2, c(0.1, 0.9)) #Trim
  data.scores_norm_trimmed <- data.scores_norm_info[data.scores_norm_info$NMDS1 > NMDS1_quantiles[1] &  
                                         data.scores_norm_info$NMDS1 < NMDS1_quantiles[2], ]
  data.scores_norm_trimmed <- data.scores_norm_info[data.scores_norm_info$NMDS2 > NMDS2_quantiles[1] &  
                                         data.scores_norm_info$NMDS2 < NMDS2_quantiles[2], ]
  data.scores_norm_trimmed <- subset(data.scores_norm_trimmed, file_code != "ERR2228534")


data.scores_norm_trimmed$ecosystem[data.scores_norm_trimmed$ecosystem %in% c("coastal")] <- "Coastal"
data.scores_norm_trimmed$ecosystem[data.scores_norm_trimmed$ecosystem %in% c("oceanic")] <- "Oceanic"

grp.a <- data.scores_norm_trimmed[data.scores_norm_trimmed$ecosystem == "Oceanic", ][chull(data.scores_norm_trimmed[data.scores_norm_trimmed$ecosystem == 
    "Oceanic", c("NMDS1", "NMDS2")]), ]  # hull values for ecosystem A
grp.b <- data.scores_norm_trimmed[data.scores_norm_trimmed$ecosystem == "Coastal", ][chull(data.scores_norm_trimmed[data.scores_norm_trimmed$ecosystem == 
    "Coastal", c("NMDS1", "NMDS2")]), ]  # hull values for ecosystem B

hull.data <- rbind(grp.a, grp.b)  #combine grp.a and grp.b


NMDS_plot_trimmed_ecosystem_2 <- ggplot() + 
  geom_polygon(data=hull.data,aes(x=NMDS1,y=NMDS2,fill=ecosystem,group=ecosystem),alpha=0.30) + # add the convex hulls
  geom_point(data=data.scores_norm_trimmed,aes(x=NMDS1,y=NMDS2, colour=ecosystem, shape = temp_Class),size=1.2) + # add the point markers
  scale_colour_manual(values=c("Oceanic" = "blue", "Coastal" = "red")) +
  geom_point() +
  theme_bw() +
 theme(axis.text.x = element_blank(),
       axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_blank(),
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 8)) +
labs(fill = "Ecosystem", color = "Ecosystem", shape = "Temperature Class")

grp.c2 <- data.scores_norm_trimmed[data.scores_norm_trimmed$temp_Class == "Tropical", ][chull(data.scores_norm_trimmed[data.scores_norm_trimmed$temp_Class == 
    "Tropical", c("NMDS1", "NMDS2")]), ]  # hull values for ecosystem A
grp.b2 <- data.scores_norm_trimmed[data.scores_norm_trimmed$temp_Class == "Polar", ][chull(data.scores_norm_trimmed[data.scores_norm_trimmed$temp_Class == 
    "Polar", c("NMDS1", "NMDS2")]), ]  # hull values for grp B
grp.a2 <- data.scores_norm_trimmed[data.scores_norm_trimmed$temp_Class == "Temperate", ][chull(data.scores_norm_trimmed[data.scores_norm_trimmed$temp_Class == 
    "Temperate", c("NMDS1", "NMDS2")]), ]  # hull values for grp B

hull.data2 <- rbind(grp.a2, grp.b2, grp.c2)  #combine grp.a and grp.b

NMDS_plot_trimmed_ecosystem_3 <- ggplot() +  
  geom_polygon(data = hull.data2, aes(x = NMDS1, y = NMDS2, fill = temp_Class, group = temp_Class), alpha = 0.30) +
  geom_point(data = data.scores_norm_trimmed, aes(x = NMDS1, y = NMDS2, shape = ecosystem, colour = temp_Class), size = 1.2) +
  scale_colour_manual(values = c("Tropical" = "blue", "Polar" = "red", "Temperate" = "green")) +
  geom_point() +
  theme_bw() +
 theme(axis.text.x = element_blank(),
       axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_blank(),
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 8)) +
  labs(fill = "Temperature Class", shape = "Ecosystem", color = "Temperature Class")
  

NMDS_plot_trimmed_ecosystem_2
NMDS_plot_trimmed_ecosystem_3

ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/NMDS_plot_trimmed_temp_x_ecosystem", ".pdf"),
       plot = NMDS_plot_trimmed_ecosystem_2,
       width = 14,
       height = 10,
       units = "cm",
       bg = "white")
ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/NMDS_plot_trimmed_temp", ".pdf"),
       plot = NMDS_plot_trimmed_ecosystem_3,
       width = 12,
       height = 8,
       units = "cm",
       bg = "white")

NMDS_plot_trimmed_ecosystem_3 <- ggplot() +  
  geom_polygon(data = hull.data2, aes(x = NMDS1, y = NMDS2, fill = temp_Class, group = temp_Class), alpha = 0.30) +
  geom_point(data = data.scores_norm_trimmed, aes(x = NMDS1, y = NMDS2, shape = ecosystem, colour = temp_Class), size = 1.2) +
  scale_colour_manual(values = c("Tropical" = "blue", "Polar" = "red", "Temperate" = "green")) +
  geom_point() +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_blank()) +
  labs(shape = "Ecosystem", fill = "Temperature Class", color = "Temperature Class")


 labs(fill = "Average Annual Nitrate"~(mg/m^-3), shape = "Ocean Classification", color = "Average Nitrate"~(mg/m^-3))
```


```{r Figure Improvement}

# Same graphs but with specific axis! 

NMDS_plot_trimmed_ecosystem_4<- ggplot() + 
  #geom_polygon(data=hull.data,aes(x=NMDS1,y=NMDS2,fill=ecosystem,group=ecosystem),alpha=0.30) + # add the convex hulls
  geom_point(data=data.scores_norm_info,aes(x=NMDS1,y=NMDS2,colour=ecosystem),size=1.2) + # add the point markers
  scale_colour_manual(values=c("oceanic" = "blue", "coastal" = "red")) +
  geom_point() +
  theme_bw() +
theme(axis.text.x = element_blank(),  # remove x-axis text
        axis.text.y = element_blank(), # remove y-axis text
        axis.ticks = element_blank(),  # remove axis ticks
        axis.title.x = element_text(size=18), # remove x-axis labels
        axis.title.y = element_text(size=18), # remove y-axis labels
        panel.background = element_blank(), 
        panel.grid.major = element_blank(),  #remove major-grid labels
        panel.grid.minor = element_blank(),  #remove minor-grid labels
        plot.background = element_blank()) +
labs(fill = "Ecosystem", color = "Ecosystem")
# xlim(-0.023, 0.01)

NMDS_plot_trimmed_ecosystem_5<- ggplot() +  
 # geom_polygon(data = hull.data2, aes(x = NMDS1, y = NMDS2, fill = temp_Class, group = temp_Class), alpha = 0.30) +
  geom_point(data = data.scores_norm_info, aes(x = NMDS1, y = NMDS2, shape = Nitrate_Class, colour = temp_woa), size = 1.2) +
  #scale_colour_manual(values = c("Tropical" = "blue", "Polar" = "red", "Temperate" = "green")) +
  geom_point() +
  theme_bw() +
  theme(axis.text.x = element_blank(),
       axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_blank(),
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 8)) +
  labs(fill = ("Average Temperature"~(phantom()^o*C)), shape = "Trophic State (Nitrate)", color = ("Average Temperature"~(phantom()^o*C))) +
xlim(-0.038, -0.026) +
ylim(-0.019, -0.008)

NMDS_plot_trimmed_ecosystem_5
  
  
ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/NMDS_plot_trimmed_ecosystem_corrected", ".pdf"),
       plot = NMDS_plot_trimmed_ecosystem_4,
       width = 12,
       height = 10,
       units = "cm",
       bg = "white")
ggsave(filename = paste0("/Users/matt/Desktop/Work/PhD/Research/Bioinformatics/Data/Figures/NMDS_plot_trimmed_temp_x_trophic_corrected", ".pdf"),
       plot = NMDS_plot_trimmed_ecosystem_5,
       width = 14,
       height = 10,
       units = "cm",
       bg = "white")

```
 

```{r EnvFit}

env <-select(data.scores_norm_info, 50:52) # Metadata

en <- envfit(NMDS_Chloro_top, env, permutations = 999, na.rm = TRUE)

data.scores = as.data.frame(scores(NMDS_Chloro_top)$sites)
data.scores$temp_Class = data.scores$temp_Class
data.scores$ecosystem = data.scores$ecosystem

en_coord_cont = as.data.frame(scores(en, "vectors")) * ordiArrowMul(en)
en_coord_cat = as.data.frame(scores(en, "factors")) * ordiArrowMul(en)

Envfit_Temp = ggplot(data = data.scores_norm_trimmed, aes(x = NMDS1, y = NMDS2)) + 
     geom_point(data = data.scores_norm_trimmed, aes(colour = temp_Class), size = 3, alpha = 0.5) + 
     scale_colour_manual(values = c("red", "blue","green"))  + 
     geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
       data = en_coord_cont, size =1, alpha = 0.5, colour = "grey30") +
   # geom_point(data = en_coord_cat, aes(x = NMDS1, y = NMDS2), 
    #   shape = "diamond", size = 4, alpha = 0.6, colour = "navy") +
     #geom_text(data = en_coord_cat, aes(x = NMDS1, y = NMDS2+0.04), 
     #  label = row.names(en_coord_cat), colour = "navy", fontface = "bold") + 
     geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30", 
       fontface = "bold", label = row.names(en_coord_cont)) + 
     theme(axis.title = element_text(size = 10, face = "bold", colour = "grey30"), 
       panel.background = element_blank(), panel.border = element_rect(fill = NA, colour = "grey30"), 
       axis.ticks = element_blank(), axis.text = element_blank(), legend.key = element_blank(), 
       legend.title = element_text(size = 10, face = "bold", colour = "grey30"), 
       legend.text = element_text(size = 9, colour = "grey30")) + 
     labs(colour = "XXX")
     
Envfit_Temp 
```
